version: '2.2'
services:
  elasticsearch1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.5.4"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - transport.host=127.0.0.1
      - "ELASTIC_PASSWORD=secret"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - esnet
  kibana:
    image: "docker.elastic.co/kibana/kibana:6.5.4"
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch1:9200"
      - "ELASTICSEARCH_PASSWORD=secret"
    hostname: kibana
    links:
      - elasticsearch1
    ports:
      - "5601:5601"
    networks:
      - esnet
  PostgreSQL:
    restart: always
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=booksdb
    volumes:
      - ./modules/core/src/main/resources/tables.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  esdata1:
    driver: local

networks:
  esnet:

